Repository pasqal-io/qadence, pull requests merged in 2023-10, with the labels that each got.

#57 [Docs,Infra] Build documentation
  .github/workflows/build_docs.yml
  .github/workflows/test_docs.yml
  README.md
  mkdocs.yml
  pyproject.toml
  readthedocs.yml
Labels: documentation, infra

#55 [Docs] Harmonise README with docs.
  .github/workflows/lint.yml
  .github/workflows/test_fast.yml
  README.md
  pyproject.toml
Labels: documentation

#59 [Infra] Refactor fast tests, package publish, docs deployment into one action
  .github/workflows/build_docs.yml
  .github/workflows/publish.yml
  .github/workflows/test_fast.yml
Labels: infra

#60 [Infra] Fix docs deploy action
  .github/workflows/test_fast.yml
Labels: infra

#62 [Infra] Fix type in github action tag condition
  .github/workflows/test_fast.yml
Labels: infra

#63 [Infra] Correct tag name in docs deployment
  .github/workflows/test_fast.yml
Labels: infra

#69 Display correct pip install command in README and index.md
  README.md
  docs/index.md
Labels: documentation

#70 [Testing] Use pytest-xdist
  pyproject.toml
Labels: testing

#75 [Docs] Fix links to tutorials in README.md
  README.md
Labels: documentation

#73 [Documentation] Add CONTRIBUTING and CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  mkdocs.yml
Labels: documentation

#76 [Infra] Add pypi and license badges
  .github/workflows/build_docs.yml
  .github/workflows/lint.yml
  .github/workflows/test_fast.yml
  README.md
Labels: infra

#80 [Testing] Remove test_notebooks
  pyproject.toml
  tests/test_notebooks.py
Labels: testing

#89 [Release] v1.0.1
  pyproject.toml
  tests/test_execution.py
Labels: release

#91 [Docs] Fixed and improved QCL example
  docs/qml/qaoa.md
  docs/qml/qcl.md
Labels: documentation

#82 [Docs] Docs improvements
  docs/digital_analog_qc/analog-basics.md
  docs/digital_analog_qc/analog-qubo.md
  docs/digital_analog_qc/daqc-cnot.md
  docs/digital_analog_qc/pulser-basic.md
  mkdocs.yml
Labels: documentation

#106 [Docs] Added install from source paragraph
  README.md
  docs/index.md
Labels: documentation

#46 [Feat] Generalizing and updating the feature_map constructor function
  docs/qml/index.md
  examples/draw.py
  qadence/constructors/feature_maps.py
  qadence/parameters.py
  qadence/types.py
  tests/constructors/test_feature_maps.py
  tests/qadence/test_matrices.py
  tests/qadence/test_measurements/test_tomography.py
Labels: feature, digital-analog

#109 [Docs] Improve README
  README.md
  pyproject.toml
Labels: documentation

#112 [Release] v0.1.2
  pyproject.toml
Labels: release

#92 [Docs] Feature maps and QML reorganization
  docs/development/draw.md
  docs/qml/index.md
  docs/qml/ml_tools.md
  docs/qml/qaoa.md
  docs/qml/qcl.md
  docs/qml/qml_constructors.md
  docs/qml/qml_tools.md
  docs/tutorials/parameters.md
  docs/tutorials/quantummodels.md
  mkdocs.yml
Labels: documentation, digital-analog

#118 [Feat] Add CSWAP to braket backend
  qadence/backends/braket/convert_ops.py
  tests/backends/braket/test_quantum_braket.py
Labels: feature

#114 Add local RZ gate for pulser backend
  qadence/backends/pulser/pulses.py
  tests/backends/pulser_basic/test_pulser_conversion.py
  tests/backends/test_pulser_pyq_compat.py
Labels: feature, core-dev

#147 [Bug fix] Fix pulser initial state passing
  qadence/backends/pulser/backend.py
  tests/backends/test_endianness.py
  tests/backends/test_pulser_pyq_compat.py
Labels: bug, backends
