Repository pasqal-io/qadence, pull requests merged in 2023-11, with the labels that each got.

#156 [Fix] Printing of nqubit blocks
  qadence/blocks/primitive.py
  tests/qadence/test_blocks.py
Labels: bug

#117 Cloud interface implementation in pulser backend
  docs/digital_analog_qc/pulser-basic.md
  pyproject.toml
  qadence/backends/pulser/backend.py
  qadence/backends/pulser/cloud.py
  qadence/backends/pulser/config.py
  qadence/execution.py
Labels: core-dev, backends

#159 [Fix] Pass diffmode in execution
  qadence/backends/pytorch_wrapper.py
  qadence/execution.py
Labels: bug

#135 [Refactor] Train loop; make sure qadence runs on GPUs correctly
  .gitignore
  .pre-commit-config.yaml
  docs/qadence/ml_tools.md
  docs/qml/ml_tools.md
  pyproject.toml
  qadence/ml_tools/__init__.py
  qadence/ml_tools/data.py
  qadence/ml_tools/optimize_step.py
  qadence/ml_tools/train_grad.py
  qadence/ml_tools/train_no_grad.py
  tests/ml_tools/test_checkpointing.py
  tests/ml_tools/test_train.py
  tests/ml_tools/test_train_no_grad.py
Labels: bug, infra

#162 [Fix] Braket CPHASE always having fixed parameters
  qadence/backends/braket/convert_ops.py
  tests/backends/test_backends.py
Labels: bug

#137 [Fix] Emulated analog results and add unit tests
  docs/digital_analog_qc/analog-qubo.md
  docs/qadence/transpile.md
  docs/tutorials/register.md
  examples/digital-analog/fit-sin.py
  examples/digital-analog/qubo.py
  qadence/__init__.py
  qadence/analog/__init__.py
  qadence/analog/interaction.py
  qadence/analog/utils.py
  qadence/backends/pulser/backend.py
  qadence/backends/pyqtorch/config.py
  qadence/blocks/analog.py
  qadence/transpile/__init__.py
  qadence/transpile/block.py
  qadence/transpile/digitalize.py
  qadence/transpile/flatten.py
  qadence/transpile/invert.py
  qadence/types.py
  tests/analog/test_analog_block.py
  tests/analog/test_analog_emulation.py
  tests/analog/test_pyq_vs_pulser.py
  tests/backends/test_gpsr.py
Labels: digital-analog, refactoring

#168 [Refac] Cleanup imports
  examples/backends/low_level/braket_digital.py
  examples/models/quantum_model.py
  qadence/analog/interaction.py
  qadence/analog/utils.py
  qadence/backends/__init__.py
  qadence/backends/api.py
  qadence/backends/braket/backend.py
  qadence/backends/pulser/backend.py
  qadence/blocks/matrix.py
  qadence/execution.py
  qadence/measurements/shadow.py
  qadence/measurements/tomography.py
  qadence/models/qnn.py
  qadence/models/quantum_model.py
  qadence/overlap.py
  qadence/parameters.py
  qadence/states.py
  tests/analog/test_analog_emulation.py
  tests/analog/test_pyq_vs_pulser.py
  tests/backends/braket/test_quantum_braket.py
  tests/backends/pulser_basic/test_configuration.py
  tests/backends/pulser_basic/test_rotations.py
  tests/backends/pyq/test_quantum_pyq.py
  tests/backends/test_endianness.py
  tests/conftest.py
  tests/metrics.py
  tests/ml_tools/test_model_parameters.py
  tests/models/test_qnn.py
  tests/models/test_quantum_model.py
  tests/qadence/test_dagger.py
  tests/qadence/test_decompose.py
  tests/qadence/test_matrixblock.py
  tests/qadence/test_measurements/test_shadows.py
  tests/qadence/test_measurements/test_tomography.py
  tests/qadence/test_observable.py
  tests/qadence/test_operators.py
  tests/qadence/test_overlap.py
  tests/qadence/test_parameters.py
  tests/qadence/test_register.py
  tests/qadence/test_transpile.py
  tests/strategies.py
  tests/test_execution.py
Labels: refactoring

#158 [Feature] Added Rydberg HEA
  docs/digital_analog_qc/index.md
  docs/digital_analog_qc/rydberg-hea.md
  docs/qadence/constructors.md
  mkdocs.yml
  qadence/constructors/__init__.py
  qadence/constructors/rydberg_hea.py
  tests/constructors/test_rydberg_hea.py
  tests/ml_tools/test_train_no_grad.py
Labels: feature, digital-analog

#171 [Refac] Cleaning up deprecated methods and avoid direct torch imports
  qadence/backends/pyqtorch/convert_ops.py
  qadence/constructors/hamiltonians.py
  qadence/execution.py
  qadence/parameters.py
  qadence/states.py
  qadence/types.py
  qadence/utils.py
  tests/analog/test_analog_emulation.py
  tests/backends/braket/test_quantum_braket.py
  tests/backends/pulser_basic/test_quantum_pulser.py
  tests/backends/test_endianness.py
  tests/conftest.py
  tests/constructors/test_ansatz.py
  tests/constructors/test_hamiltonians.py
  tests/constructors/test_qft.py
  tests/qadence/test_measurements/test_tomography.py
  tests/qadence/test_states.py
  tests/test_serialize.py
Labels: refactoring

#128 [Feature] Implementation of noise protocol.
  docs/realistic_sims/index.md
  docs/realistic_sims/measurements.md
  docs/realistic_sims/mitigation.md
  docs/realistic_sims/noise.md
  mkdocs.yml
  qadence/__init__.py
  qadence/backend.py
  qadence/backends/braket/backend.py
  qadence/backends/braket/convert_ops.py
  qadence/backends/pulser/backend.py
  qadence/backends/pyqtorch/backend.py
  qadence/backends/pytorch_wrapper.py
  qadence/blocks/utils.py
  qadence/errors/__init__.py
  qadence/exceptions/__init__.py
  qadence/exceptions/exceptions.py
  qadence/execution.py
  qadence/measurements/shadow.py
  qadence/measurements/tomography.py
  qadence/ml_tools/models.py
  qadence/models/qnn.py
  qadence/models/quantum_model.py
  qadence/noise/__init__.py
  qadence/noise/protocols.py
  qadence/noise/readout.py
  qadence/overlap.py
  tests/backends/test_backends.py
  tests/qadence/test_error_models.py
  tests/qadence/test_measurements/test_shadows.py
  tests/qadence/test_measurements/test_tomography.py
Labels: feature, realistic-sim

#155 [Feature] Pyqtorch - First Order Adjoint Differentiation
  examples/models/quantum_model.py
  qadence/backend.py
  qadence/backends/adjoint.py
  qadence/backends/braket/backend.py
  qadence/backends/pulser/backend.py
  qadence/backends/pyqtorch/backend.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/backends/pytorch_wrapper.py
  qadence/backends/utils.py
  qadence/extensions.py
  qadence/types.py
  tests/backends/pyq/test_quantum_pyq.py
  tests/backends/test_adjoint.py
  tests/backends/test_pytorch_wrapper.py
  tests/conftest.py
  tests/metrics.py
  tests/ml_tools/test_train.py
  tests/models/test_qnn.py
  tests/models/test_quantum_model.py
  tests/test_execution.py
Labels: feature, performance

#195 [Fix] Export Toffoli gate in operations.py
  qadence/operations.py
Labels: bug

#189 [Refactoring] Improve mitigation protocol
  qadence/backend.py
  qadence/backends/braket/backend.py
  qadence/backends/pulser/backend.py
  qadence/backends/pyqtorch/backend.py
  qadence/mitigations/analog_zne.py
  qadence/mitigations/protocols.py
  qadence/mitigations/readout.py
  qadence/noise/protocols.py
  qadence/types.py
  tests/qadence/test_mitigation.py
Labels: refactoring

#210 [Fix] `fill_identities` which caused drawing issues
  docs/development/draw.md
  pyproject.toml
  qadence/draw/utils.py
  qadence/transpile/block.py
  tests/qadence/test_mitigation.py
Labels: bug
