Repository pasqal-io/qadence, pull requests merged in 2023-12, with the labels that each got.

#212 [Fix] Validate state and parameter batch sizes
  qadence/backend.py
  qadence/backends/braket/backend.py
  qadence/backends/pulser/backend.py
  qadence/backends/pyqtorch/backend.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/backends/pytorch_wrapper.py
  qadence/backends/utils.py
  qadence/utils.py
Labels: refactoring

#176 [Refactoring, Feature] More modular add interaction and qubit device prototype
  docs/digital_analog_qc/analog-basics.md
  docs/digital_analog_qc/analog-qcl.md
  docs/digital_analog_qc/analog-qubo.md
  docs/digital_analog_qc/pulser-basic.md
  docs/digital_analog_qc/rydberg-hea.md
  docs/digital_analog_qc/semi-local-addressing.md
  docs/tutorials/hamiltonians.md
  docs/tutorials/register.md
  examples/digital-analog/qubo.py
  mkdocs.yml
  qadence/analog/__init__.py
  qadence/analog/addressing.py
  qadence/analog/constants.py
  qadence/analog/device.py
  qadence/analog/hamiltonian_terms.py
  qadence/analog/interaction.py
  qadence/analog/parse_analog.py
  qadence/analog/utils.py
  qadence/backends/pulser/__init__.py
  qadence/backends/pulser/backend.py
  qadence/backends/pulser/config.py
  qadence/backends/pulser/devices.py
  qadence/backends/pulser/pulses.py
  qadence/backends/pyqtorch/config.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/blocks/analog.py
  qadence/constructors/hamiltonians.py
  qadence/register.py
  qadence/transpile/__init__.py
  qadence/transpile/apply_fn.py
  qadence/types.py
  tests/analog/test_analog_emulation.py
  tests/analog/test_patterns.py
  tests/analog/test_pyq_vs_pulser.py
  tests/backends/pulser_basic/test_entanglement.py
  tests/backends/pulser_basic/test_pulser_conversion.py
  tests/backends/test_gpsr.py
  tests/qadence/test_register.py
  tests/qadence/test_transpile.py
Labels: digital-analog, refactoring

#219 [Fix] Dagger Methods in ControlBlocks and Scaleblock
  qadence/blocks/abstract.py
  qadence/blocks/analog.py
  qadence/blocks/primitive.py
  qadence/extensions.py
  qadence/operations.py
  qadence/parameters.py
  tests/qadence/test_dagger.py
Labels: bug

#243 [BugFix] Fix parameters arithmetic.
  qadence/backends/pulser/pulses.py
  qadence/operations.py
  tests/analog/test_pyq_vs_pulser.py
  tests/backends/pulser_basic/test_rotations.py
Labels: bug

#244 [Feature] Allow turning off the semi-local addressing pattern in pyqtorch backend
  docs/digital_analog_qc/semi-local-addressing.md
  qadence/analog/parse_analog.py
  qadence/backends/pulser/pulses.py
  qadence/blocks/analog.py
  qadence/operations.py
  tests/analog/test_patterns.py
Labels: digital-analog

#234 [Feature] Analog feature maps
  docs/digital_analog_qc/rydberg-hea.md
  docs/digital_analog_qc/semi-local-addressing.md
  mkdocs.yml
  qadence/constructors/__init__.py
  qadence/constructors/feature_maps.py
  qadence/constructors/rydberg_feature_maps.py
  tests/constructors/test_rydberg_hea.py
Labels: feature, digital-analog

#111 [Engines, Backends] Add JAX Engine and Horqrux Backend
  README.md
  docs/advanced_tutorials/differentiability.md
  docs/backends/differentiable.md
  docs/development/architecture.md
  docs/tutorials/backends.md
  examples/backends/differentiable_backend.py
  examples/backends/low_level/horqrux_backend.py
  pyproject.toml
  qadence/__init__.py
  qadence/backend.py
  qadence/backends/__init__.py
  qadence/backends/api.py
  qadence/backends/braket/backend.py
  qadence/backends/horqrux/__init__.py
  qadence/backends/horqrux/backend.py
  qadence/backends/horqrux/config.py
  qadence/backends/horqrux/convert_ops.py
  qadence/backends/jax_utils.py
  qadence/backends/pulser/backend.py
  qadence/backends/pyqtorch/backend.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/backends/utils.py
  qadence/blocks/embedding.py
  qadence/engines/__init__.py
  qadence/engines/differentiable_backend.py
  qadence/engines/jax/__init__.py
  qadence/engines/jax/differentiable_backend.py
  qadence/engines/jax/differentiable_expectation.py
  qadence/engines/torch/__init__.py
  qadence/engines/torch/differentiable_backend.py
  qadence/engines/torch/differentiable_expectation.py
  qadence/extensions.py
  qadence/models/quantum_model.py
  qadence/parameters.py
  qadence/types.py
  tests/backends/horqrux/test_quantum_horqrux.py
  tests/backends/pulser_basic/test_differentiation.py
  tests/backends/test_backends.py
  tests/backends/test_endianness.py
  tests/backends/test_gpsr.py
  tests/engines/test_torch.py
  tests/metrics.py
Labels: feature, backends, engines

#254 [Fix] Handling transformation of multi-dimensional input in Transform…
  qadence/ml_tools/models.py
Labels: bug

#276 [Bugfix] Fix projector matrices
  qadence/blocks/block_to_tensor.py
  tests/qadence/test_matrices.py
Labels: bug

#269 [Docs] Add projector docs
  docs/advanced_tutorials/index.md
  docs/advanced_tutorials/projectors.md
  mkdocs.yml
Labels: documentation

#225 [Feature] ZNE for pulse stretching
  qadence/backends/pulser/backend.py
  qadence/mitigations/analog_zne.py
  tests/qadence/test_mitigation.py
Labels: feature

#265 [Docs] Add mitigation docs
  docs/realistic_sims/mitigation.md
  docs/realistic_sims/noise.md
Labels: documentation

#277 [Docs] Add docs measurements
  docs/realistic_sims/measurements.md
Labels: documentation

#274 [Feature] Add trainable frequency feature maps
  docs/qml/qml_constructors.md
  qadence/constructors/feature_maps.py
  qadence/constructors/rydberg_feature_maps.py
  tests/constructors/test_feature_maps.py
Labels: feature
