Repository pasqal-io/qadence, pull requests merged in 2024-02, with the labels that each got.

#308 [Fix] Correctly move models to GPU
  pyproject.toml
  qadence/backends/pyqtorch/convert_ops.py
  qadence/ml_tools/models.py
  qadence/models/quantum_model.py
Labels: bug

#317 [Refact] Organize operations file into folder
  pyproject.toml
  qadence/backends/braket/convert_ops.py
  qadence/backends/pulser/pulses.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/blocks/utils.py
  qadence/measurements/shadow.py
  qadence/measurements/tomography.py
  qadence/operations.py
  qadence/operations/__init__.py
  qadence/operations/analog.py
  qadence/operations/control_ops.py
  qadence/operations/ham_evo.py
  qadence/operations/parametric.py
  qadence/operations/primitive.py
  tests/analog/test_analog_emulation.py
  tests/backends/braket/test_quantum_braket.py
  tests/qadence/test_block_utils.py
  tests/qadence/test_mitigation.py
Labels: refactoring

#318 [Fix] PyQ HamEvo/ Observable GPU buffer fixes, Add device to block_to_tensor
  pyproject.toml
  qadence/backends/pyqtorch/convert_ops.py
  qadence/blocks/block_to_tensor.py
  qadence/ml_tools/train_grad.py
Labels: bug

#316 [Fix] Add inputs to qnn deserialize, add serialization of noise and mitigation in QM
  qadence/backends/horqrux/backend.py
  qadence/models/qnn.py
  qadence/models/quantum_model.py
Labels: bug

#319 [BugFix] Wrong tensor for control blocks, inefficient eigenvalues
  qadence/blocks/primitive.py
  qadence/utils.py
  tests/qadence/test_matrices.py
Labels: bug, refactoring

#330 [Refac] Add 'device' to ml_tools optimize_step
  pyproject.toml
  qadence/ml_tools/data.py
  qadence/ml_tools/optimize_step.py
  qadence/ml_tools/train_grad.py
Labels: refactoring, breaking

#338 [Feature] Add JAX / Horqrux HamiltonianEvolution
  examples/backends/low_level/horqrux_analog.py
  pyproject.toml
  qadence/backends/horqrux/backend.py
  qadence/backends/horqrux/config.py
  qadence/backends/horqrux/convert_ops.py
  qadence/backends/jax_utils.py
  qadence/backends/utils.py
  qadence/blocks/__init__.py
  qadence/execution.py
  qadence/utils.py
  tests/backends/test_backends.py
  tests/backends/test_endianness.py
Labels: feature

#349 [Docs] Improve qaoa tutorial
  docs/qml/qaoa.md
Labels: documentation
