Repository pasqal-io/qadence, pull requests merged in 2024-09, with the labels that each got.

#554 [Feature] Add possibility to modify the OptimizeResult during training in ml_tools
  docs/tutorials/qml/ml_tools.md
  qadence/ml_tools/__init__.py
  qadence/ml_tools/config.py
  qadence/ml_tools/train_grad.py
Labels: feature

#557 [Release] Bump version to 1.7.7
  pyproject.toml
Labels: release

#560 [BugFix] Fix writer callback
  qadence/ml_tools/train_grad.py
Labels: bug

#566 [Feature] Add tagging option to QNN configs
  qadence/ml_tools/config.py
  qadence/ml_tools/constructors.py
Labels: feature
