Repository pasqal-io/qadence, pull requests merged in 2024-07, with the labels that each got.

#393 [Feature] Time-dependent generator proposal
  docs/content/time_dependent.md
  mkdocs.yml
  qadence/backends/gpsr.py
  qadence/backends/pyqtorch/backend.py
  qadence/backends/pyqtorch/config.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/backends/utils.py
  qadence/blocks/abstract.py
  qadence/blocks/embedding.py
  qadence/execution.py
  qadence/model.py
  qadence/operations/ham_evo.py
  qadence/parameters.py
  qadence/types.py
  tests/backends/pyq/test_time_dependent_generator.py
  tests/conftest.py
  tests/engines/test_torch.py
  tests/metrics.py
  tests/qadence/test_measurements/test_sample_expectation.py
  tests/qadence/test_quantum_model.py
Labels: feature, digital-analog, proto, block-system, hamevo

#487 [Documentation] Improve QuantumModel docstrings
  qadence/model.py
Labels: documentation

#477 [Refac] Fix saving/loading models with device
  pyproject.toml
  qadence/ml_tools/saveload.py
  qadence/ml_tools/train_grad.py
  tests/ml_tools/test_checkpointing.py
Labels: refactoring

#494 [Fix] Use sympy<1.13
  pyproject.toml
Labels: bug

#490 [Feature] Add backend, diff mode etc to config constructor
  docs/tutorials/qml/config_qnn.md
  qadence/ml_tools/config.py
  qadence/ml_tools/constructors.py
  qadence/ml_tools/models.py
  tests/ml_tools/test_qnn.py
Labels: feature

#496 [Bug] Fix backend import if in extensions.
  qadence/extensions.py
Labels: bug

#497 Bump version.
  pyproject.toml
Labels: release

#499 [Feature] Allow loss_fn in train_grad to return arbitrary number of values.
  docs/tutorials/qml/ml_tools.md
  qadence/ml_tools/train_grad.py
Labels: feature

#450 [Feature] Add mlflow experiment tracker
  .gitignore
  docs/tutorials/qml/ml_tools.md
  pyproject.toml
  qadence/ml_tools/config.py
  qadence/ml_tools/printing.py
  qadence/ml_tools/train_grad.py
  qadence/ml_tools/train_no_grad.py
  qadence/types.py
  tests/ml_tools/test_logging.py
Labels: feature

#507 [Refactor] Minor code base clean-up
  .github/dependabot.yml
  .github/workflows/dependabot.yml
  pyproject.toml
Labels: refactoring

#510 [Bug] Fix MLFlow import, and setup function that caused tests to fail
  qadence/ml_tools/config.py
  qadence/ml_tools/printing.py
  tests/ml_tools/test_logging.py
Labels: bug

#512 [Release] Bump version to 1.7.4
  pyproject.toml
Labels: release

#515 AnsatzConfig Updates, Correct
  qadence/ml_tools/constructors.py
Labels: bug
