Repository pasqal-io/qadence, pull requests merged in 2024-01, with the labels that each got.

#283 [Refact] Import PI
  docs/digital_analog_qc/analog-basics.md
  docs/digital_analog_qc/daqc-cnot.md
  docs/digital_analog_qc/pulser-basic.md
  docs/digital_analog_qc/semi-local-addressing.md
  docs/index.md
  docs/tutorials/overlap.md
  docs/tutorials/parameters.md
  docs/tutorials/register.md
  docs/tutorials/state_conventions.md
  qadence/analog/addressing.py
  qadence/analog/device.py
  qadence/backends/gpsr.py
  qadence/backends/pulser/devices.py
  qadence/backends/pulser/pulses.py
  qadence/blocks/block_to_tensor.py
  qadence/constructors/feature_maps.py
  qadence/constructors/iia.py
  qadence/constructors/qft.py
  qadence/constructors/rydberg_feature_maps.py
  qadence/constructors/utils.py
  qadence/operations.py
  qadence/states.py
  qadence/types.py
  tests/analog/test_analog_block.py
  tests/analog/test_analog_emulation.py
  tests/analog/test_patterns.py
  tests/analog/test_pyq_vs_pulser.py
  tests/backends/pulser_basic/test_configuration.py
  tests/backends/pulser_basic/test_differentiation.py
  tests/backends/pulser_basic/test_entanglement.py
  tests/backends/pulser_basic/test_pulser_conversion.py
  tests/backends/pulser_basic/test_quantum_pulser.py
  tests/backends/pulser_basic/test_rotations.py
  tests/backends/pyq/test_quantum_pyq.py
  tests/backends/test_backends.py
  tests/backends/test_endianness.py
  tests/backends/test_gpsr.py
  tests/conftest.py
  tests/constructors/test_feature_maps.py
  tests/constructors/test_qft.py
  tests/constructors/test_rydberg_hea.py
  tests/engines/test_torch.py
  tests/models/test_quantum_model.py
  tests/qadence/test_blocks.py
  tests/qadence/test_mitigation.py
  tests/qadence/test_overlap.py
  tests/qadence/test_parameters.py
  tests/strategies.py
Labels: refactoring

#284 [Refact] Replace alias wait with AnalogInteraction
  docs/digital_analog_qc/analog-basics.md
  docs/digital_analog_qc/analog-qcl.md
  docs/digital_analog_qc/pulser-basic.md
  docs/qadence/operations.md
  examples/digital-analog/fit-sin.py
  examples/draw.py
  qadence/analog/parse_analog.py
  qadence/backend.py
  qadence/backends/pulser/pulses.py
  qadence/blocks/analog.py
  qadence/blocks/utils.py
  qadence/draw/utils.py
  qadence/mitigations/analog_zne.py
  qadence/operations.py
  qadence/types.py
  tests/analog/test_analog_block.py
  tests/analog/test_analog_emulation.py
  tests/analog/test_pyq_vs_pulser.py
  tests/backends/pulser_basic/test_differentiation.py
Labels: refactoring

#286 [Documentation] Improved analog QUBO tutorial
  docs/digital_analog_qc/analog-qubo.md
  pyproject.toml
Labels: documentation

#289 [Feature] Added SDAQC strategy for IIA
  qadence/constructors/iia.py
  tests/constructors/test_ansatz.py
Labels: feature, digital-analog

#294 [Bugfix] Add measurements and mitigation to expectation
  qadence/execution.py
Labels: bug

#295 [Refac Fix] Use backend directly in measurements
  qadence/engines/torch/differentiable_expectation.py
  qadence/measurements/shadow.py
  qadence/measurements/tomography.py
  tests/metrics.py
  tests/qadence/test_measurements/test_shadows.py
  tests/qadence/test_measurements/test_tomography.py
Labels: bug, refactoring

#292 [Docs] Add adjoint differentiation to docs
  docs/advanced_tutorials/differentiability.md
Labels: documentation

#299 [Release] Bump to 1.2.4
  pyproject.toml
Labels: release

#293 [Feature] Allow custom interactions in the hamiltonian factory
  docs/tutorials/hamiltonians.md
  qadence/constructors/hamiltonians.py
  qadence/operations.py
  tests/constructors/test_hamiltonians.py
Labels: feature, digital-analog

#301 [Infra] Add logo and change colors
  README.md
  docs/css/mkdocstrings.css
  docs/index.md
  docs/logo/qadence_logo.svg
  docs/logo/qadence_logo_small_white.svg
  docs/logo/qadence_logo_white.svg
  mkdocs.yml
Labels: documentation, infra
