Repository pasqal-io/qadence, pull requests merged in 2024-05, with the labels that each got.

#404 [CoreDev] Remove deprecations
  docs/api/backends/braket.md
  docs/content/backends.md
  docs/tutorials/digital_analog_qc/pulser-basic.md
  examples/backends/low_level/braket_digital.py
  examples/backends/low_level/horqrux_dqc.py
  examples/models/qnn.py
  mkdocs.yml
  qadence/backends/pulser/backend.py
  qadence/backends/pulser/config.py
  qadence/constructors/__init__.py
  qadence/constructors/ansatze.py
  qadence/constructors/feature_maps.py
  qadence/constructors/hamiltonians.py
  qadence/extensions.py
  qadence/operations/__init__.py
  qadence/operations/analog.py
  tests/backends/braket/test_quantum_braket.py
  tests/qadence/test_blocks.py
Labels: core-dev

#409 [Refactor] Remove setting noise model in sample call.
  qadence/models/quantum_model.py
Labels: refactoring

#410 [Bug] Correct SimConfig syntax.
  qadence/backends/pulser/backend.py
Labels: bug

#415 [Infra] Fix Renovate config
  pyproject.toml
  renovate.json
Labels: infra

#420 [Infra] More fixes renovate config
  renovate.json
Labels: infra

#425 [Fix] Allow numpy numeric types in Parameters
  qadence/types.py
  tests/qadence/test_parameters.py
Labels: bug
