Repository pasqal-io/qadence, pull requests merged in 2024-06, with the labels that each got.

#439 Bump version.
  pyproject.toml
Labels: release

#440 [Performance] Cache non-parametric pulser observable
  qadence/backends/pulser/convert_ops.py
Labels: performance

#442 [Performance] Improve horqrux sampling
  qadence/backends/horqrux/backend.py
Labels: performance

#437 [Refac] Add `backend` argument to `product_state` function
  qadence/states.py
  tests/qadence/test_states.py
Labels: refactoring

#454 [Infra] Update pulser dependencies
  pyproject.toml
Labels: infra

#435 [Feature] Add `checkpoint_best_only` to `train_grad`
  docs/tutorials/qml/ml_tools.md
  qadence/ml_tools/config.py
  qadence/ml_tools/printing.py
  qadence/ml_tools/saveload.py
  qadence/ml_tools/train_grad.py
  tests/ml_tools/test_train.py
Labels: feature

#460 [Bug] Fix ci failing tests
  tests/metrics.py
  tests/qadence/test_measurements/test_sample_expectation.py
Labels: bug

#462 Bump version.
  pyproject.toml
Labels: release

#466 [Fix] Remove jax import in `states` module
  pyproject.toml
  qadence/ml_tools/saveload.py
  qadence/parameters.py
  qadence/states.py
Labels: bug

#467 [Documentation] Add WSL and Windows instructions
  README.md
Labels: documentation

#406 [Refac] Use native pytorch higher-order blocks and Adjoint Differentiation
  pyproject.toml
  qadence/backends/adjoint.py
  qadence/backends/pyqtorch/backend.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/engines/torch/differentiable_expectation.py
  tests/backends/horqrux/test_quantum_horqrux.py
  tests/backends/pyq/test_quantum_pyq.py
  tests/backends/test_adjoint.py
  tests/engines/test_torch.py
Labels: backends

#464 [Docs] Fix pipeline
  pyproject.toml
  qadence/blocks/matrix.py
Labels: bug, documentation

#385 [Feature | Refac | Breaking] Rework QNN, Remove TransformedModule, Add Configs
  docs/api/ml_tools.md
  docs/api/models.md
  docs/content/quantummodels.md
  docs/tutorials/development/architecture.md
  docs/tutorials/qml/config_qnn.md
  docs/tutorials/qml/ml_tools.md
  docs/tutorials/qml/qcl.md
  examples/quick_start.py
  mkdocs.yml
  pyproject.toml
  qadence/__init__.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/backends/utils.py
  qadence/blocks/matrix.py
  qadence/blocks/primitive.py
  qadence/constructors/__init__.py
  qadence/constructors/hamiltonians.py
  qadence/draw/utils.py
  qadence/finitediff.py
  qadence/ml_tools/__init__.py
  qadence/ml_tools/config.py
  qadence/ml_tools/constructors.py
  qadence/ml_tools/models.py
  qadence/ml_tools/saveload.py
  qadence/ml_tools/train_grad.py
  qadence/ml_tools/utils.py
  qadence/model.py
  qadence/models/__init__.py
  qadence/models/qnn.py
  qadence/overlap.py
  qadence/serialization.py
  qadence/types.py
  tests/analog/test_pyq_vs_pulser.py
  tests/backends/pulser_basic/test_rotations.py
  tests/backends/pyq/test_quantum_pyq.py
  tests/backends/test_backends.py
  tests/conftest.py
  tests/constructors/test_rydberg_hea.py
  tests/engines/test_torch.py
  tests/ml_tools/test_checkpointing.py
  tests/ml_tools/test_model_parameters.py
  tests/ml_tools/test_qnn.py
  tests/ml_tools/test_train.py
  tests/ml_tools/test_transformed_module.py
  tests/qadence/test_decompose.py
  tests/qadence/test_error_models.py
  tests/qadence/test_manipulate.py
  tests/qadence/test_matrixblock.py
  tests/qadence/test_measurements/test_shadows.py
  tests/qadence/test_measurements/test_tomography.py
  tests/qadence/test_parameters.py
  tests/qadence/test_quantum_model.py
  tests/test_finitediff.py
  tests/test_serialize.py
Labels: refactoring, breaking

#360 [Refactor] Error logging and refac of backend_factory
  qadence/backends/api.py
  qadence/extensions.py
Labels: refactoring
