Repository pasqal-io/qadence, pull requests merged in 2024-08, with the labels that each got.

#526 [Refact] Factor 2 for Hamevo spectral gap in GPSR
  qadence/blocks/utils.py
  qadence/engines/torch/differentiable_expectation.py
  tests/metrics.py
Labels: hamevo

#528 [Fix] Adapt shift prefactor with hamevo
  qadence/backends/gpsr.py
  qadence/blocks/utils.py
  qadence/engines/jax/differentiable_expectation.py
  qadence/engines/torch/differentiable_expectation.py
  tests/metrics.py
Labels: bug

#529 [Bugfix] Divide shift by spectral gap for single-gap PSR
  qadence/blocks/utils.py
Labels: bug

#519 [Fix] Consistent naming and using of StrEnums instead of string literals
  qadence/constructors/utils.py
  qadence/ml_tools/config.py
  qadence/ml_tools/constructors.py
  qadence/types.py
Labels: bug, breaking

#533 [Feature] Adding callback functionalities in train functions
  docs/tutorials/qml/ml_tools.md
  pyproject.toml
  qadence/ml_tools/__init__.py
  qadence/ml_tools/config.py
  qadence/ml_tools/data.py
  qadence/ml_tools/optimize_step.py
  qadence/ml_tools/train_grad.py
  qadence/ml_tools/train_no_grad.py
Labels: feature, proto

#531 [Refactor] Use PyQ's time-independent Hamiltonian evolution
  qadence/backends/pyqtorch/convert_ops.py
  tests/backends/test_adjoint.py
Labels: refactoring

#540 [Feature] Add issue template
  .github/workflows/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/ISSUE_TEMPLATE/config.yml
  .github/workflows/ISSUE_TEMPLATE/new-feature.yml
Labels: documentation

#543 Callbacks after optimization are run without modulo check
  qadence/ml_tools/config.py
  qadence/ml_tools/train_grad.py
  qadence/ml_tools/train_no_grad.py
Labels: bug, enhancement

#546 [Bug] Fix `write_checkpoint` bug
  pyproject.toml
  qadence/ml_tools/saveload.py
Labels: bug

#550 [BugFix] Fix parameters passed as complex convert_ops
  qadence/backends/pyqtorch/convert_ops.py
Labels: bug
