Repository pasqal-io/qadence, pull requests merged in 2024-10, with the labels that each got.

#568 [Refact] Get rid of PyQTimeDependentEvolution
  docs/content/time_dependent.md
  qadence/backends/pyqtorch/convert_ops.py
  qadence/blocks/embedding.py
  qadence/operations/ham_evo.py
  tests/analog/test_patterns.py
  tests/backends/pyq/test_time_dependent_generator.py
  tests/backends/test_gpsr.py
  tests/conftest.py
  tests/engines/test_torch.py
  tests/qadence/test_quantum_model.py
Labels: refactoring

#563 [Feature] Add digital noise from PyQ
  docs/content/block_system.md
  docs/tutorials/realistic_sims/noise.md
  qadence/backends/pyqtorch/convert_ops.py
  qadence/backends/utils.py
  qadence/blocks/matrix.py
  qadence/blocks/primitive.py
  qadence/noise/__init__.py
  qadence/noise/protocols.py
  qadence/operations/control_ops.py
  qadence/operations/parametric.py
  qadence/operations/primitive.py
  qadence/transpile/__init__.py
  qadence/transpile/noise.py
  qadence/types.py
Labels: feature

#591 [Refactoring] [Testing] [Feature] NoiseHandler
  docs/api/noise.md
  docs/tutorials/realistic_sims/mitigation.md
  docs/tutorials/realistic_sims/noise.md
  mkdocs.yml
  pyproject.toml
  qadence/backend.py
  qadence/backends/braket/backend.py
  qadence/backends/horqrux/backend.py
  qadence/backends/pulser/backend.py
  qadence/backends/pulser/convert_ops.py
  qadence/backends/pyqtorch/backend.py
  qadence/backends/pyqtorch/convert_ops.py
  qadence/blocks/matrix.py
  qadence/blocks/primitive.py
  qadence/engines/differentiable_backend.py
  qadence/engines/jax/differentiable_backend.py
  qadence/engines/jax/differentiable_expectation.py
  qadence/engines/torch/differentiable_backend.py
  qadence/engines/torch/differentiable_expectation.py
  qadence/execution.py
  qadence/measurements/shadow.py
  qadence/measurements/tomography.py
  qadence/measurements/utils.py
  qadence/mitigations/analog_zne.py
  qadence/mitigations/protocols.py
  qadence/mitigations/readout.py
  qadence/ml_tools/constructors.py
  qadence/ml_tools/models.py
  qadence/model.py
  qadence/noise/__init__.py
  qadence/noise/protocols.py
  qadence/operations/control_ops.py
  qadence/operations/parametric.py
  qadence/operations/primitive.py
  qadence/transpile/noise.py
  qadence/types.py
  tests/backends/pulser_basic/test_quantum_pulser.py
  tests/qadence/test_noise/test_digital_noise.py
  tests/qadence/test_noise/test_readout.py
Labels: documentation, feature, testing, refactoring
