Repository pasqal-io/qadence, pull requests merged in 2025-03, with the labels that each got.

#702 [Bug] Fix `networkx` deprecation warning
  qadence/register.py
Labels: bug

#713 [Documentation] Updating Qadence QNN documentation
  docs/content/quantummodels.md
  qadence/backend.py
  qadence/model.py
  tests/backends/test_backends.py
  tests/ml_tools/test_qnn.py
  tests/qadence/test_quantum_model.py
Labels: documentation, enhancement

#719 [Refactoring] Disable save checkpoint when checkpoint_every==0
  qadence/ml_tools/callbacks/callbackmanager.py
Labels: refactoring
