Repository pasqal-io/qadence, pull requests merged in 2025-02, with the labels that each got.

#658 Add config constructor to use QNN with ALA ansatz
  qadence/ml_tools/config.py
  qadence/ml_tools/constructors.py
  qadence/types.py
  tests/ml_tools/test_qnn.py
Labels: feature

#665 [Refactor] Remove additional run() calls when importing qadence
  qadence/utils.py
Labels: bug

#662 [Docs] Adding Noisy Simulation documentation
  docs/content/noisy_simulation.md
  docs/tutorials/realistic_sims/noise.md
  mkdocs.yml
Labels: documentation

#681 [Feature] Add __str__ representation for quantum model
  qadence/ml_tools/models.py
  qadence/utils.py
  tests/ml_tools/test_qnn.py
  tests/test_str_utils.py
Labels: feature

#686 [Feature] use_full_support default to False for block_to_tensor
  qadence/blocks/block_to_tensor.py
  qadence/mitigations/analog_zne.py
  tests/qadence/test_matrices.py
  tests/qadence/test_operators.py
Labels: enhancement

#687 [Testing] Projector tests
  tests/qadence/test_matrices.py
  tests/qadence/test_operators.py
Labels: testing

#689 [Feature] Add parametric blocks support for block_to_diagonal
  qadence/blocks/block_to_tensor.py
  tests/qadence/test_matrices.py
Labels: feature
